package com.example.licicat

import java.sql.Timestamp

data class Licitacio(
    var codi_ambit: String? = null,
    var nom_ambit: String? = null,
    var codi_departament_ens: String? = null,
    var nom_departament_ens: String? = null,
    var codi_organ: String? = null,
    var nom_organ: String? = null,
    var codi_unitat: Int? = null,
    var nom_unitat: String? = null,
    var codi_ine10: String? = null,
    var codi_dir3: String? = null,
    var codi_expedient: String? = null,
    var tipus_contracte: String? = null,
    var subtipus_contracte: String? = null,
    var procediment: String? = null,
    var fase_publicacio: String? = null,
    var denominacio: String? = null,
    var objecte_contracte: String? = null,
    var pressupost_licitacio: Int? = null,
    var valor_estimat_contracte: Int? = null,
    var codi_nuts: String? = null,
    var lloc_execucio: String? = null,
    var duracio_contracte: String? = null,
    var termini_presentacio_ofertes: String? = null,
    var data_publicacio_futura: Timestamp? = null,
    var data_publicacio_previ: Timestamp? = null,
    var data_publicacio_anunci: Timestamp? = null,
    var data_publicacio_adjudicacio: Timestamp? = null,
    var data_publicacio_formalitzacio: String? = null,
    var data_publicacio_anul: Timestamp? = null,
    var numero_lot: String? = null,
    var descripcio_lot: String? = null,
    var codi_cpv: String? = null,
    var tipus_identificacio: String? = null,
    var identificacio_adjudicatari: String? = null,
    var denominacio_adjudicatari: String? = null,
    var import_adjudicacio_sense: Int? = null,
    var import_adjudicacio_amb_iva: Int? = null,
    var ofertes_rebudes: Int? = null,
    var resultat: String? = null,
    var enllac_publicacio: String? = null,
    var es_agregada: String? = null,
    var data_adjudicacio_contracte: Timestamp? = null,
    var data_formalitzacio_contracte: Timestamp? = null,
    var pressupost_licitacio_asString: String ? = null
)