name: Codacy Analysis

on:
  pull_request:
    branches: [ '*' ]

jobs:
  codacy-analysis:
    name: Codacy Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Codacy analysis
        uses: codacy/codacy-analysis-action@3.0.2
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
